ge <- readRDS("/path/to/xelox_reanalysis/input/gene_expr.rds"); v <- as.numeric(ge)
cat("gene_expr.rds dim:", paste(dim(ge), collapse=" x "), "\n")
cat("  min/median/max:", sprintf("%.2f / %.2f / %.2f", min(v,na.rm=TRUE), median(v,na.rm=TRUE), max(v,na.rm=TRUE)), "\n")
cat("  scale verdict:", if (max(v,na.rm=TRUE) > 40) "LINEAR - would contaminate the headline" else "log2 - unaffected by the scale defect", "\n")
cat("  cols:", paste(head(colnames(ge),3), collapse=", "), " ...\n")
ps <- read.csv("/path/to/xelox_reanalysis/input/pathway_scores.csv", row.names=1, check.names=FALSE)
cat("pathway_scores:", paste(dim(ps), collapse=" x "), "  range", sprintf("%.2f..%.2f", min(as.numeric(as.matrix(ps)),na.rm=TRUE), max(as.numeric(as.matrix(ps)),na.rm=TRUE)), "\n")
cl <- read.csv("/path/to/xelox_reanalysis/input/clinical.csv", check.names=FALSE)
cat("clinical rows:", nrow(cl), " events:", sum(cl$rfs_event, na.rm=TRUE), "\n")
