library(Biobase)
cat("Loading eset...\n")
eset <- readRDS("C:/xelox_research/data/geo/GSE39582_eset.rds")
cat("Loaded.\n")
expr <- exprs(eset)
cat("DIM:", nrow(expr), ncol(expr), "\n")
cat("RANGE:", range(expr, na.rm=TRUE), "\n")
rms <- rowMeans(expr, na.rm=TRUE)
cat("MEAN_ROWMEAN:", mean(rms), "\n")
cat("MEDIAN_ROWMEAN:", median(rms), "\n")
cat("SD_ROWMEAN:", sd(rms), "\n")
for (thr in c(5,6,7,8,9,10)) cat(sprintf("GT_%d: %d\n", thr, sum(rms > thr)))
cat(sprintf("GT_MEDIAN_2SD: %d\n", sum(rms > median(rms)+2*sd(rms))))
cat(sprintf("GT_MEDIAN_1SD: %d\n", sum(rms > median(rms)+1*sd(rms))))
cat("Done.\n")
